using CommunityToolkit.Mvvm.Messaging;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SIG.ClientCard.App.Services;
using SIG.ClientCard.App.ViewModels;
using SIG.ClientCard.App.Views;
using SIG.ClientCard.Core.Abstractions;
using SIG.ClientCard.Data;
using SIG.ClientCard.Data.CompiledModels;
using SIG.ClientCard.Data.Infrastructure;
using SIG.ClientCard.Data.Repositories;
using SIG.ClientCard.Sync;
using SIG.ClientCard.Sync.Transport;

namespace SIG.ClientCard.App;

public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder.UseMauiApp<App>();

        var services = builder.Services;

        // ------------------------------------------------------------ core services
        services.AddSingleton<IClock, SystemClock>();
        services.AddSingleton<IDeviceIdentity, DeviceIdentity>();
        services.AddSingleton<ITenantContext, LocalTenantContext>();
        services.AddSingleton<DatabaseKeyProvider>();
        services.AddSingleton<OutboxWriter>();
        services.AddSingleton<IMessenger>(WeakReferenceMessenger.Default);

        // ------------------------------------------------------------ database
        services.AddDbContextFactory<ClientCardContext>((sp, options) =>
        {
            var keys = sp.GetRequiredService<DatabaseKeyProvider>();
            var dbPath = Path.Combine(FileSystem.AppDataDirectory, "clientcard.db3");

            // Password= issues PRAGMA key against the SQLCipher build on open.
            options.UseSqlite($"Data Source={dbPath};Password={keys.GetOrCreateKey(dbPath)}")
                // Compiled model: EF's runtime model build costs 300-600ms on
                // mid-range Android at first query. Regenerated by
                // `dotnet ef dbcontext optimize` after every migration.
                .UseModel(ClientCardContextModel.Instance)
                .AddInterceptors(new SqlitePragmaInterceptor());
        });

        // ------------------------------------------------------------ repositories
        services.AddSingleton<IClientRepository, ClientRepository>();
        services.AddSingleton<IClientNoteRepository, ClientNoteRepository>();
        services.AddSingleton<IServiceRecordRepository, ServiceRecordRepository>();
        services.AddSingleton<IClientConsentRepository, ClientConsentRepository>();

        // ------------------------------------------------------------ sync
        services.AddSingleton(new SyncOptions());
        if (SupabaseConfig.IsConfigured)
        {
            services.AddSingleton<IAccessTokenProvider, SupabaseTokenProvider>();
            services.AddSingleton<ISyncTransport>(sp =>
            {
                var handler = new SupabaseAuthHandler(
                    sp.GetRequiredService<IAccessTokenProvider>(), SupabaseConfig.AnonKey)
                {
                    InnerHandler = new HttpClientHandler(),
                };
                var http = new HttpClient(handler) { BaseAddress = new Uri(SupabaseConfig.Url) };
                return new SupabaseSyncTransport(http);
            });
        }
        else
        {
            // Phase 0: local only. Writes queue in the outbox and drain once a
            // Supabase project is configured.
            services.AddSingleton<ISyncTransport, OfflineSyncTransport>();
        }

        services.AddSingleton<SyncEngine>();
        services.AddSingleton<SyncScheduler>();

        // ------------------------------------------------------------ views + viewmodels
        services.AddSingleton<ClientsViewModel>();
        services.AddSingleton<ClientsPage>();
        services.AddTransient<ClientDetailViewModel>();
        services.AddTransient<ClientDetailPage>();
        services.AddTransient<ClientEditViewModel>();
        services.AddTransient<ClientEditPage>();
        services.AddTransient<AddServiceViewModel>();
        services.AddTransient<AddServicePage>();
        services.AddTransient<AddNoteViewModel>();
        services.AddTransient<AddNotePage>();
        services.AddSingleton<SyncStatusViewModel>();
        services.AddSingleton<AppShell>();

        var app = builder.Build();

        // Apply migrations before any page queries the database.
        using (var scope = app.Services.CreateScope())
        {
            var factory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<ClientCardContext>>();
            using var db = factory.CreateDbContext();
            db.Database.Migrate();
        }

        return app;
    }
}
