<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIG.ClientCard.Core\SIG.ClientCard.Core.csproj" />
    <ProjectReference Include="..\SIG.ClientCard.Data\SIG.ClientCard.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SIG.ClientCard.Tests" />
  </ItemGroup>

</Project>
