// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIG.ClientCard.Data;

#nullable disable

namespace SIG.ClientCard.Data.Migrations
{
    [DbContext(typeof(ClientCardContext))]
    [Migration("20260728143423_AddReconcileTracking")]
    partial class AddReconcileTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SIG.ClientCard.Core.Entities.Client", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AcquisitionDetail")
                        .HasColumnType("TEXT")
                        .HasColumnName("acquisition_detail");

                    b.Property<int>("AcquisitionSource")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acquisition_source");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("CardPhotoPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("card_photo_path");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_birth");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("GpDetails")
                        .HasColumnType("TEXT")
                        .HasColumnName("gp_details");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<bool>("MedicalFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medical_flag");

                    b.Property<DateOnly?>("PatchTestOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("patch_test_on");

                    b.Property<int>("PatchTestResult")
                        .HasColumnType("INTEGER")
                        .HasColumnName("patch_test_result");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("PhoneRaw")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_raw");

                    b.Property<string>("SalonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("salon_id");

                    b.Property<long>("SyncSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sync_seq");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByDevice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_device");

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName");

                    b.HasIndex("SalonId", "SyncSeq");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("SIG.ClientCard.Core.Entities.ClientConsent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CapturedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_by_user_id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_at");

                    b.Property<long>("GrantedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("granted_at");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purpose");

                    b.Property<string>("SalonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("salon_id");

                    b.Property<string>("SignatureBlobRef")
                        .HasColumnType("TEXT")
                        .HasColumnName("signature_blob_ref");

                    b.Property<long>("SyncSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sync_seq");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByDevice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_device");

                    b.Property<long?>("WithdrawnAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Purpose");

                    b.HasIndex("SalonId", "SyncSeq");

                    b.ToTable("client_consent", (string)null);
                });

            modelBuilder.Entity("SIG.ClientCard.Core.Entities.ClientNote", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AuthorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_at");

                    b.Property<string>("SalonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("salon_id");

                    b.Property<long>("SyncSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sync_seq");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByDevice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_device");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "CreatedAt");

                    b.HasIndex("SalonId", "SyncSeq");

                    b.ToTable("client_note", (string)null);
                });

            modelBuilder.Entity("SIG.ClientCard.Core.Entities.Salon", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("RetentionYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retention_years");

                    b.HasKey("Id");

                    b.ToTable("salon", (string)null);
                });

            modelBuilder.Entity("SIG.ClientCard.Core.Entities.ServiceRecord", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly>("PerformedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("performed_on");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("photo_path");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("SalonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("salon_id");

                    b.Property<string>("ServiceCatalogId")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_catalog_id");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("service_description");

                    b.Property<long>("SyncSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sync_seq");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByDevice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_device");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "PerformedOn");

                    b.HasIndex("SalonId", "SyncSeq");

                    b.ToTable("service_record", (string)null);
                });

            modelBuilder.Entity("SIG.ClientCard.Data.Entities.SyncDeadLetterEntry", b =>
                {
                    b.Property<string>("OpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("op_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempts");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<long>("ParkedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parked_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.HasKey("OpId");

                    b.ToTable("sync_dead_letter", (string)null);
                });

            modelBuilder.Entity("SIG.ClientCard.Data.Entities.SyncOutboxEntry", b =>
                {
                    b.Property<string>("OpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("op_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempts");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<long?>("NextAttemptAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.HasKey("OpId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_created");

                    b.ToTable("sync_outbox", (string)null);
                });

            modelBuilder.Entity("SIG.ClientCard.Data.Entities.SyncStateRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Cursor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cursor");

                    b.Property<long?>("LastPullAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_pull_at");

                    b.Property<long?>("LastPushAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_push_at");

                    b.Property<long?>("LastReconcileAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_reconcile_at");

                    b.HasKey("Id");

                    b.ToTable("sync_state", (string)null);
                });

            modelBuilder.Entity("SIG.ClientCard.Core.Entities.ClientConsent", b =>
                {
                    b.HasOne("SIG.ClientCard.Core.Entities.Client", null)
                        .WithMany("Consents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIG.ClientCard.Core.Entities.ClientNote", b =>
                {
                    b.HasOne("SIG.ClientCard.Core.Entities.Client", null)
                        .WithMany("Notes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIG.ClientCard.Core.Entities.ServiceRecord", b =>
                {
                    b.HasOne("SIG.ClientCard.Core.Entities.Client", null)
                        .WithMany("Services")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIG.ClientCard.Core.Entities.Client", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Notes");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
