// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SIG.ClientCard.Core.Entities;
using SIG.ClientCard.Core.Enums;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SIG.ClientCard.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ClientEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SIG.ClientCard.Core.Entities.Client",
                typeof(Client),
                baseEntityType,
                propertyCount: 20,
                navigationCount: 3,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new GuidToLowerStringConverter());
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var acquisitionDetail = runtimeEntityType.AddProperty(
                "AcquisitionDetail",
                typeof(string),
                propertyInfo: typeof(Client).GetProperty("AcquisitionDetail", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<AcquisitionDetail>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            acquisitionDetail.AddAnnotation("Relational:ColumnName", "acquisition_detail");

            var acquisitionSource = runtimeEntityType.AddProperty(
                "AcquisitionSource",
                typeof(AcquisitionSource),
                propertyInfo: typeof(Client).GetProperty("AcquisitionSource", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<AcquisitionSource>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            acquisitionSource.SetSentinelFromProviderValue(0);
            acquisitionSource.AddAnnotation("Relational:ColumnName", "acquisition_source");

            var address = runtimeEntityType.AddProperty(
                "Address",
                typeof(string),
                propertyInfo: typeof(Client).GetProperty("Address", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<Address>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            address.AddAnnotation("Relational:ColumnName", "address");

            var cardPhotoPath = runtimeEntityType.AddProperty(
                "CardPhotoPath",
                typeof(string),
                propertyInfo: typeof(Client).GetProperty("CardPhotoPath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<CardPhotoPath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            cardPhotoPath.AddAnnotation("Relational:ColumnName", "card_photo_path");

            var dateOfBirth = runtimeEntityType.AddProperty(
                "DateOfBirth",
                typeof(DateOnly?),
                propertyInfo: typeof(Client).GetProperty("DateOfBirth", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<DateOfBirth>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            dateOfBirth.AddAnnotation("Relational:ColumnName", "date_of_birth");

            var deletedAt = runtimeEntityType.AddProperty(
                "DeletedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(SyncedEntity).GetProperty("DeletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<DeletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new NullableDateTimeOffsetToUtcTicksConverter());
            deletedAt.AddAnnotation("Relational:ColumnName", "deleted_at");

            var email = runtimeEntityType.AddProperty(
                "Email",
                typeof(string),
                propertyInfo: typeof(Client).GetProperty("Email", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<Email>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            email.AddAnnotation("Relational:ColumnName", "email");

            var firstName = runtimeEntityType.AddProperty(
                "FirstName",
                typeof(string),
                propertyInfo: typeof(Client).GetProperty("FirstName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<FirstName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            firstName.AddAnnotation("Relational:ColumnName", "first_name");

            var gpDetails = runtimeEntityType.AddProperty(
                "GpDetails",
                typeof(string),
                propertyInfo: typeof(Client).GetProperty("GpDetails", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<GpDetails>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            gpDetails.AddAnnotation("Relational:ColumnName", "gp_details");

            var lastName = runtimeEntityType.AddProperty(
                "LastName",
                typeof(string),
                propertyInfo: typeof(Client).GetProperty("LastName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<LastName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            lastName.AddAnnotation("Relational:ColumnName", "last_name");

            var medicalFlag = runtimeEntityType.AddProperty(
                "MedicalFlag",
                typeof(bool),
                propertyInfo: typeof(Client).GetProperty("MedicalFlag", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<MedicalFlag>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            medicalFlag.AddAnnotation("Relational:ColumnName", "medical_flag");

            var patchTestOn = runtimeEntityType.AddProperty(
                "PatchTestOn",
                typeof(DateOnly?),
                propertyInfo: typeof(Client).GetProperty("PatchTestOn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<PatchTestOn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            patchTestOn.AddAnnotation("Relational:ColumnName", "patch_test_on");

            var patchTestResult = runtimeEntityType.AddProperty(
                "PatchTestResult",
                typeof(PatchTestResult),
                propertyInfo: typeof(Client).GetProperty("PatchTestResult", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<PatchTestResult>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            patchTestResult.SetSentinelFromProviderValue(0);
            patchTestResult.AddAnnotation("Relational:ColumnName", "patch_test_result");

            var phone = runtimeEntityType.AddProperty(
                "Phone",
                typeof(string),
                propertyInfo: typeof(Client).GetProperty("Phone", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<Phone>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            phone.AddAnnotation("Relational:ColumnName", "phone");

            var phoneRaw = runtimeEntityType.AddProperty(
                "PhoneRaw",
                typeof(string),
                propertyInfo: typeof(Client).GetProperty("PhoneRaw", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<PhoneRaw>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            phoneRaw.AddAnnotation("Relational:ColumnName", "phone_raw");

            var salonId = runtimeEntityType.AddProperty(
                "SalonId",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("SalonId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<SalonId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new GuidToLowerStringConverter());
            salonId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            salonId.AddAnnotation("Relational:ColumnName", "salon_id");

            var syncSeq = runtimeEntityType.AddProperty(
                "SyncSeq",
                typeof(long),
                propertyInfo: typeof(SyncedEntity).GetProperty("SyncSeq", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<SyncSeq>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            syncSeq.AddAnnotation("Relational:ColumnName", "sync_seq");

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(SyncedEntity).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new DateTimeOffsetToUtcTicksConverter());
            updatedAt.SetSentinelFromProviderValue(0L);
            updatedAt.AddAnnotation("Relational:ColumnName", "updated_at");

            var updatedByDevice = runtimeEntityType.AddProperty(
                "UpdatedByDevice",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("UpdatedByDevice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<UpdatedByDevice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new GuidToLowerStringConverter());
            updatedByDevice.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            updatedByDevice.AddAnnotation("Relational:ColumnName", "updated_by_device");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { lastName, firstName });

            var index0 = runtimeEntityType.AddIndex(
                new[] { salonId, syncSeq });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "client");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
