// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SIG.ClientCard.Core.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SIG.ClientCard.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ClientNoteEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SIG.ClientCard.Core.Entities.ClientNote",
                typeof(ClientNote),
                baseEntityType,
                propertyCount: 10,
                foreignKeyCount: 1,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new GuidToLowerStringConverter());
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var authorUserId = runtimeEntityType.AddProperty(
                "AuthorUserId",
                typeof(Guid?),
                propertyInfo: typeof(ClientNote).GetProperty("AuthorUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClientNote).GetField("<AuthorUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new NullableGuidToLowerStringConverter());
            authorUserId.AddAnnotation("Relational:ColumnName", "author_user_id");

            var body = runtimeEntityType.AddProperty(
                "Body",
                typeof(string),
                propertyInfo: typeof(ClientNote).GetProperty("Body", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClientNote).GetField("<Body>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            body.AddAnnotation("Relational:ColumnName", "body");

            var clientId = runtimeEntityType.AddProperty(
                "ClientId",
                typeof(Guid),
                propertyInfo: typeof(ClientNote).GetProperty("ClientId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClientNote).GetField("<ClientId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new GuidToLowerStringConverter());
            clientId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            clientId.AddAnnotation("Relational:ColumnName", "client_id");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ClientNote).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClientNote).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new DateTimeOffsetToUtcTicksConverter());
            createdAt.SetSentinelFromProviderValue(0L);
            createdAt.AddAnnotation("Relational:ColumnName", "created_at");

            var deletedAt = runtimeEntityType.AddProperty(
                "DeletedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(SyncedEntity).GetProperty("DeletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<DeletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new NullableDateTimeOffsetToUtcTicksConverter());
            deletedAt.AddAnnotation("Relational:ColumnName", "deleted_at");

            var salonId = runtimeEntityType.AddProperty(
                "SalonId",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("SalonId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<SalonId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new GuidToLowerStringConverter());
            salonId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            salonId.AddAnnotation("Relational:ColumnName", "salon_id");

            var syncSeq = runtimeEntityType.AddProperty(
                "SyncSeq",
                typeof(long),
                propertyInfo: typeof(SyncedEntity).GetProperty("SyncSeq", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<SyncSeq>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            syncSeq.AddAnnotation("Relational:ColumnName", "sync_seq");

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(SyncedEntity).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new DateTimeOffsetToUtcTicksConverter());
            updatedAt.SetSentinelFromProviderValue(0L);
            updatedAt.AddAnnotation("Relational:ColumnName", "updated_at");

            var updatedByDevice = runtimeEntityType.AddProperty(
                "UpdatedByDevice",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("UpdatedByDevice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<UpdatedByDevice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new GuidToLowerStringConverter());
            updatedByDevice.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            updatedByDevice.AddAnnotation("Relational:ColumnName", "updated_by_device");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { clientId, createdAt });

            var index0 = runtimeEntityType.AddIndex(
                new[] { salonId, syncSeq });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ClientId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var notes = principalEntityType.AddNavigation("Notes",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<ClientNote>),
                propertyInfo: typeof(Client).GetProperty("Notes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<Notes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "client_note");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
