// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using SIG.ClientCard.Data;
using SIG.ClientCard.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ClientCardContext), typeof(ClientCardContextModel))]
