// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SIG.ClientCard.Data.CompiledModels
{
    public partial class ClientCardContextModel
    {
        private ClientCardContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("22f8499d-4a54-44dc-95e1-4afe606b2855"), entityTypeCount: 10)
        {
        }

        partial void Initialize()
        {
            var client = ClientEntityType.Create(this);
            var clientConsent = ClientConsentEntityType.Create(this);
            var clientNote = ClientNoteEntityType.Create(this);
            var salon = SalonEntityType.Create(this);
            var serviceCatalogItem = ServiceCatalogItemEntityType.Create(this);
            var serviceRecord = ServiceRecordEntityType.Create(this);
            var attachmentQueueEntry = AttachmentQueueEntryEntityType.Create(this);
            var syncDeadLetterEntry = SyncDeadLetterEntryEntityType.Create(this);
            var syncOutboxEntry = SyncOutboxEntryEntityType.Create(this);
            var syncStateRow = SyncStateRowEntityType.Create(this);

            ClientConsentEntityType.CreateForeignKey1(clientConsent, client);
            ClientNoteEntityType.CreateForeignKey1(clientNote, client);
            ServiceRecordEntityType.CreateForeignKey1(serviceRecord, client);

            ClientEntityType.CreateAnnotations(client);
            ClientConsentEntityType.CreateAnnotations(clientConsent);
            ClientNoteEntityType.CreateAnnotations(clientNote);
            SalonEntityType.CreateAnnotations(salon);
            ServiceCatalogItemEntityType.CreateAnnotations(serviceCatalogItem);
            ServiceRecordEntityType.CreateAnnotations(serviceRecord);
            AttachmentQueueEntryEntityType.CreateAnnotations(attachmentQueueEntry);
            SyncDeadLetterEntryEntityType.CreateAnnotations(syncDeadLetterEntry);
            SyncOutboxEntryEntityType.CreateAnnotations(syncOutboxEntry);
            SyncStateRowEntityType.CreateAnnotations(syncStateRow);

            AddAnnotation("ProductVersion", "10.0.10");
        }
    }
}
