// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SIG.ClientCard.Core.Entities;
using SIG.ClientCard.Core.Enums;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SIG.ClientCard.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ClientConsentEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SIG.ClientCard.Core.Entities.ClientConsent",
                typeof(ClientConsent),
                baseEntityType,
                propertyCount: 12,
                foreignKeyCount: 1,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new GuidToLowerStringConverter());
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var capturedByUserId = runtimeEntityType.AddProperty(
                "CapturedByUserId",
                typeof(Guid?),
                propertyInfo: typeof(ClientConsent).GetProperty("CapturedByUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClientConsent).GetField("<CapturedByUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new NullableGuidToLowerStringConverter());
            capturedByUserId.AddAnnotation("Relational:ColumnName", "captured_by_user_id");

            var clientId = runtimeEntityType.AddProperty(
                "ClientId",
                typeof(Guid),
                propertyInfo: typeof(ClientConsent).GetProperty("ClientId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClientConsent).GetField("<ClientId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new GuidToLowerStringConverter());
            clientId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            clientId.AddAnnotation("Relational:ColumnName", "client_id");

            var deletedAt = runtimeEntityType.AddProperty(
                "DeletedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(SyncedEntity).GetProperty("DeletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<DeletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new NullableDateTimeOffsetToUtcTicksConverter());
            deletedAt.AddAnnotation("Relational:ColumnName", "deleted_at");

            var grantedAt = runtimeEntityType.AddProperty(
                "GrantedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ClientConsent).GetProperty("GrantedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClientConsent).GetField("<GrantedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new DateTimeOffsetToUtcTicksConverter());
            grantedAt.SetSentinelFromProviderValue(0L);
            grantedAt.AddAnnotation("Relational:ColumnName", "granted_at");

            var purpose = runtimeEntityType.AddProperty(
                "Purpose",
                typeof(ConsentPurpose),
                propertyInfo: typeof(ClientConsent).GetProperty("Purpose", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClientConsent).GetField("<Purpose>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            purpose.SetSentinelFromProviderValue(0);
            purpose.AddAnnotation("Relational:ColumnName", "purpose");

            var salonId = runtimeEntityType.AddProperty(
                "SalonId",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("SalonId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<SalonId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new GuidToLowerStringConverter());
            salonId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            salonId.AddAnnotation("Relational:ColumnName", "salon_id");

            var signatureBlobRef = runtimeEntityType.AddProperty(
                "SignatureBlobRef",
                typeof(string),
                propertyInfo: typeof(ClientConsent).GetProperty("SignatureBlobRef", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClientConsent).GetField("<SignatureBlobRef>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            signatureBlobRef.AddAnnotation("Relational:ColumnName", "signature_blob_ref");

            var syncSeq = runtimeEntityType.AddProperty(
                "SyncSeq",
                typeof(long),
                propertyInfo: typeof(SyncedEntity).GetProperty("SyncSeq", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<SyncSeq>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            syncSeq.AddAnnotation("Relational:ColumnName", "sync_seq");

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(SyncedEntity).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new DateTimeOffsetToUtcTicksConverter());
            updatedAt.SetSentinelFromProviderValue(0L);
            updatedAt.AddAnnotation("Relational:ColumnName", "updated_at");

            var updatedByDevice = runtimeEntityType.AddProperty(
                "UpdatedByDevice",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("UpdatedByDevice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<UpdatedByDevice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new GuidToLowerStringConverter());
            updatedByDevice.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            updatedByDevice.AddAnnotation("Relational:ColumnName", "updated_by_device");

            var withdrawnAt = runtimeEntityType.AddProperty(
                "WithdrawnAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(ClientConsent).GetProperty("WithdrawnAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ClientConsent).GetField("<WithdrawnAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new NullableDateTimeOffsetToUtcTicksConverter());
            withdrawnAt.AddAnnotation("Relational:ColumnName", "withdrawn_at");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { clientId, purpose });

            var index0 = runtimeEntityType.AddIndex(
                new[] { salonId, syncSeq });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ClientId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var consents = principalEntityType.AddNavigation("Consents",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<ClientConsent>),
                propertyInfo: typeof(Client).GetProperty("Consents", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Client).GetField("<Consents>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "client_consent");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
