// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SIG.ClientCard.Core.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SIG.ClientCard.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ServiceCatalogItemEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SIG.ClientCard.Core.Entities.ServiceCatalogItem",
                typeof(ServiceCatalogItem),
                baseEntityType,
                propertyCount: 9,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new GuidToLowerStringConverter());
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var currencyCode = runtimeEntityType.AddProperty(
                "CurrencyCode",
                typeof(string),
                propertyInfo: typeof(ServiceCatalogItem).GetProperty("CurrencyCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ServiceCatalogItem).GetField("<CurrencyCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 3);
            currencyCode.AddAnnotation("Relational:ColumnName", "currency_code");

            var defaultPrice = runtimeEntityType.AddProperty(
                "DefaultPrice",
                typeof(decimal),
                propertyInfo: typeof(ServiceCatalogItem).GetProperty("DefaultPrice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ServiceCatalogItem).GetField("<DefaultPrice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                precision: 10,
                scale: 2,
                sentinel: 0m);
            defaultPrice.AddAnnotation("Relational:ColumnName", "default_price");

            var deletedAt = runtimeEntityType.AddProperty(
                "DeletedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(SyncedEntity).GetProperty("DeletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<DeletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new NullableDateTimeOffsetToUtcTicksConverter());
            deletedAt.AddAnnotation("Relational:ColumnName", "deleted_at");

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(ServiceCatalogItem).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ServiceCatalogItem).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            name.AddAnnotation("Relational:ColumnName", "name");

            var salonId = runtimeEntityType.AddProperty(
                "SalonId",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("SalonId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<SalonId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new GuidToLowerStringConverter());
            salonId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            salonId.AddAnnotation("Relational:ColumnName", "salon_id");

            var syncSeq = runtimeEntityType.AddProperty(
                "SyncSeq",
                typeof(long),
                propertyInfo: typeof(SyncedEntity).GetProperty("SyncSeq", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<SyncSeq>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            syncSeq.AddAnnotation("Relational:ColumnName", "sync_seq");

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(SyncedEntity).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new DateTimeOffsetToUtcTicksConverter());
            updatedAt.SetSentinelFromProviderValue(0L);
            updatedAt.AddAnnotation("Relational:ColumnName", "updated_at");

            var updatedByDevice = runtimeEntityType.AddProperty(
                "UpdatedByDevice",
                typeof(Guid),
                propertyInfo: typeof(SyncedEntity).GetProperty("UpdatedByDevice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncedEntity).GetField("<UpdatedByDevice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new GuidToLowerStringConverter());
            updatedByDevice.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            updatedByDevice.AddAnnotation("Relational:ColumnName", "updated_by_device");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { name });

            var index0 = runtimeEntityType.AddIndex(
                new[] { salonId, syncSeq });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "service_catalog");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
