// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SIG.ClientCard.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SIG.ClientCard.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class SyncDeadLetterEntryEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "SIG.ClientCard.Data.Entities.SyncDeadLetterEntry",
                typeof(SyncDeadLetterEntry),
                baseEntityType,
                propertyCount: 9,
                keyCount: 1);

            var opId = runtimeEntityType.AddProperty(
                "OpId",
                typeof(Guid),
                propertyInfo: typeof(SyncDeadLetterEntry).GetProperty("OpId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncDeadLetterEntry).GetField("<OpId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new GuidToLowerStringConverter());
            opId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            opId.AddAnnotation("Relational:ColumnName", "op_id");

            var attempts = runtimeEntityType.AddProperty(
                "Attempts",
                typeof(int),
                propertyInfo: typeof(SyncDeadLetterEntry).GetProperty("Attempts", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncDeadLetterEntry).GetField("<Attempts>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            attempts.AddAnnotation("Relational:ColumnName", "attempts");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(SyncDeadLetterEntry).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncDeadLetterEntry).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new DateTimeOffsetToUtcTicksConverter());
            createdAt.SetSentinelFromProviderValue(0L);
            createdAt.AddAnnotation("Relational:ColumnName", "created_at");

            var entity = runtimeEntityType.AddProperty(
                "Entity",
                typeof(string),
                propertyInfo: typeof(SyncDeadLetterEntry).GetProperty("Entity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncDeadLetterEntry).GetField("<Entity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            entity.AddAnnotation("Relational:ColumnName", "entity");

            var entityId = runtimeEntityType.AddProperty(
                "EntityId",
                typeof(Guid),
                propertyInfo: typeof(SyncDeadLetterEntry).GetProperty("EntityId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncDeadLetterEntry).GetField("<EntityId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new GuidToLowerStringConverter());
            entityId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            entityId.AddAnnotation("Relational:ColumnName", "entity_id");

            var lastError = runtimeEntityType.AddProperty(
                "LastError",
                typeof(string),
                propertyInfo: typeof(SyncDeadLetterEntry).GetProperty("LastError", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncDeadLetterEntry).GetField("<LastError>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastError.AddAnnotation("Relational:ColumnName", "last_error");

            var operation = runtimeEntityType.AddProperty(
                "Operation",
                typeof(string),
                propertyInfo: typeof(SyncDeadLetterEntry).GetProperty("Operation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncDeadLetterEntry).GetField("<Operation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            operation.AddAnnotation("Relational:ColumnName", "operation");

            var parkedAt = runtimeEntityType.AddProperty(
                "ParkedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(SyncDeadLetterEntry).GetProperty("ParkedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncDeadLetterEntry).GetField("<ParkedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new DateTimeOffsetToUtcTicksConverter());
            parkedAt.SetSentinelFromProviderValue(0L);
            parkedAt.AddAnnotation("Relational:ColumnName", "parked_at");

            var payload = runtimeEntityType.AddProperty(
                "Payload",
                typeof(string),
                propertyInfo: typeof(SyncDeadLetterEntry).GetProperty("Payload", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncDeadLetterEntry).GetField("<Payload>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            payload.AddAnnotation("Relational:ColumnName", "payload");

            var key = runtimeEntityType.AddKey(
                new[] { opId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "sync_dead_letter");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
